const state={messages:[],citations:[],rag:'',nlu:null,busy:false,collapsed:{nlu:false,citations:false},streamIndex:-1}
const el={messages:document.getElementById('messages'),input:document.getElementById('input'),composer:document.getElementById('composer'),status:document.getElementById('status'),citations:document.getElementById('citations'),nlu:document.getElementById('nlu')}
const toast=document.getElementById('toast')
function now(){return new Date().toLocaleTimeString('zh-CN',{hour12:false})}
function renderMessages(){el.messages.innerHTML='';state.messages.forEach((m,i)=>{const box=document.createElement('div');box.className='message '+m.role;const avatar=document.createElement('div');avatar.className='avatar';avatar.textContent=m.role==='user'?'U':'A';box.appendChild(avatar);const meta=document.createElement('div');meta.className='meta';meta.textContent=(m.role==='user'?'用户':'说服智能体')+' · '+m.time;box.appendChild(meta);const text=document.createElement('div');text.textContent=m.content;box.appendChild(text);const actions=document.createElement('div');actions.className='actions';const copy=document.createElement('button');copy.className='icon-btn';copy.textContent='复制';copy.addEventListener('click',()=>{navigator.clipboard.writeText(m.content).then(()=>showToast('已复制')).catch(()=>showToast('复制失败'))});actions.appendChild(copy);box.appendChild(actions);el.messages.appendChild(box)});if(state.busy){const typing=document.createElement('div');typing.className='typing';const t=document.createElement('span');t.className='dots';typing.appendChild(t);typing.appendChild(document.createTextNode(' 正在生成'));el.messages.appendChild(typing)}el.messages.scrollTop=el.messages.scrollHeight}
function renderCitations(){const box=document.getElementById('ragBox');const btn=document.getElementById('toggleCitations');const hidden=state.collapsed.citations;btn.textContent=hidden?'展开':'折叠';box.style.display=hidden?'none':'block';box.innerHTML='';const text=state.rag&&state.rag.trim()?state.rag.trim():'';if(!text){const empty=document.createElement('div');empty.className='badge';empty.textContent='暂无引用';box.appendChild(empty);return}const pre=document.createElement('div');pre.textContent=text;box.appendChild(pre)}
function renderNLU(){const rows=document.querySelector('.nlu-rows');const s=document.getElementById('nluSentiment');const t=document.getElementById('nluStance');const c=document.getElementById('nluScene');const btn=document.getElementById('toggleNLU');const hidden=state.collapsed.nlu;btn.textContent=hidden?'展开':'折叠';rows.style.display=hidden?'none':'flex';s.textContent='';t.textContent='';c.textContent='';if(!state.nlu){s.textContent='暂无';t.textContent='暂无';c.textContent='暂无';return}s.textContent=state.nlu.sentiment||'未知';t.textContent=state.nlu.stance||'未知';c.textContent=state.nlu.scene||'未知'}
function setBusy(b){state.busy=b;el.status.textContent=b?'处理中…':'就绪';el.input.disabled=b}
function addMessage(role,content){state.messages.push({role,content,time:now()});renderMessages()}
function startAssistantStream(){state.streamIndex=state.messages.length;state.messages.push({role:'assistant',content:'',time:now()});renderMessages()}
function appendAssistantStream(chunk){if(state.streamIndex<0)return;state.messages[state.streamIndex].content+=chunk;renderMessages()}
function endAssistantStream(){state.streamIndex=-1}
async function handleSend(e){e.preventDefault();const text=el.input.value.trim();if(!text||state.busy)return;el.input.value='';addMessage('user',text);setBusy(true);state.rag='';state.nlu={sentiment:'',stance:'',scene:'',intent:'一般问答',entities:[],steps:[],confidence:0.8};renderCitations();renderNLU();startAssistantStream();await API.runFlow(text,(ev)=>{if(ev.type==='rag_chunk'){state.rag+=ev.data;renderCitations()}else if(ev.type==='rag_done'){renderCitations()}else if(ev.type==='stance'){state.nlu.stance=ev.data;renderNLU()}else if(ev.type==='sentiment'){state.nlu.sentiment=ev.data;renderNLU()}else if(ev.type==='scene'){state.nlu.scene=ev.data;renderNLU()}else if(ev.type==='reply_chunk'){appendAssistantStream(ev.data)}else if(ev.type==='reply_done'){endAssistantStream();setBusy(false)}})}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
function bindUI(){document.getElementById('clearBtn').addEventListener('click',()=>{state.messages=[];renderMessages();showToast('已清空会话')});document.getElementById('toggleNLU').addEventListener('click',()=>{state.collapsed.nlu=!state.collapsed.nlu;renderNLU()});document.getElementById('toggleCitations').addEventListener('click',()=>{state.collapsed.citations=!state.collapsed.citations;renderCitations()});document.querySelectorAll('.chip').forEach(ch=>{ch.addEventListener('click',()=>{el.input.value=ch.dataset.text;el.composer.dispatchEvent(new Event('submit'))})})}
function clearAll(){state.messages=[];state.citations=[];state.rag='';state.nlu=null;state.collapsed={nlu:false,citations:false};state.streamIndex=-1;setBusy(false);el.input.value='';renderMessages();renderCitations();renderNLU();showToast('已清空全部内容')}
function bindUI(){document.getElementById('clearBtn').addEventListener('click',clearAll);document.getElementById('toggleNLU').addEventListener('click',()=>{state.collapsed.nlu=!state.collapsed.nlu;renderNLU()});document.getElementById('toggleCitations').addEventListener('click',()=>{state.collapsed.citations=!state.collapsed.citations;renderCitations()});document.querySelectorAll('.chip').forEach(ch=>{ch.addEventListener('click',()=>{el.input.value=ch.dataset.text;el.composer.dispatchEvent(new Event('submit'))})})}
function init(){addMessage('assistant','您好，我想和你谈谈巴以冲突这个话题，请问您有什么看法呢');renderCitations();renderNLU();el.composer.addEventListener('submit',handleSend);el.input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(typeof el.composer.requestSubmit==='function'){el.composer.requestSubmit()}else{el.composer.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}}});bindUI()}
init()
