const http=require('http')
const fs=require('fs')
const path=require('path')
const url=require('url')
const root=process.cwd()
let port=process.env.PORT?Number(process.env.PORT):5500
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.txt':'text/plain','.map':'application/json'}
function send(res,status,headers,body){res.writeHead(status,headers);res.end(body)}
function serveFile(res,fp){fs.stat(fp,(e,st)=>{if(e||!st.isFile())return send(res,404,{'Content-Type':'text/plain'},'Not Found');const ext=path.extname(fp);const type=types[ext]||'application/octet-stream';fs.readFile(fp,(err,data)=>{if(err)return send(res,500,{'Content-Type':'text/plain'},'Internal Server Error');send(res,200,{'Content-Type':type},data)})})}
function json(res,status,obj){send(res,status,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"},JSON.stringify(obj))}
function readBody(req){return new Promise(r=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{r(JSON.parse(d||'{}'))}catch(e){r({})}})})}
function keywords(text){return String(text).toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').split(/\s+/).filter(w=>w.length>2).slice(0,3)}
function genCitations(query){const ks=keywords(query);const list=ks.map(k=>({title:`关于 ${k} 的权威资料`,url:`https://www.bing.com/search?q=${encodeURIComponent(k)}`,snippet:`基于公开来源检索到与「${k}」相关的结果，供参考。`}));if(!list.length){list.push({title:'通用参考资料',url:'https://www.bing.com',snippet:'未检测到关键字，提供通用参考入口。'})}return list}
function genNLU(text){const hasWhy=/为什|why/i.test(text);const hasHow=/如何|怎么|how/i.test(text);const intent=hasHow?'求解步骤':hasWhy?'原因解释':'一般问答';const numbers=(String(text).match(/\d+(\.\d+)?/g)||[]).map(v=>({type:'数值',value:v}));const dates=(String(text).match(/\d{4}[-/年]\d{1,2}([-/月]\d{1,2})?/g)||[]).map(v=>({type:'日期',value:v}));const entities=[...numbers,...dates];const steps=intent==='求解步骤'?['识别问题与目标','拆解为可执行步骤','提供示例或伪代码']:intent==='原因解释'?['定位原因或机制','结合案例说明','给出建议与改进']:['理解问题','从知识库检索','生成直接回答'];const confidence=0.6+Math.random()*0.35;const lower=String(text).toLowerCase();const positive=['好','棒','赞','喜欢','支持','优秀'];const negative=['差','不好','讨厌','反对','糟糕','问题'];const sentiment=negative.some(w=>lower.includes(w))?'消极':positive.some(w=>lower.includes(w))?'积极':'中性';const stance=lower.includes('支持')||lower.includes('赞成')?'支持':lower.includes('反对')||lower.includes('不同意')?'反对':'中立';const scene=lower.includes('产品')?'产品':lower.includes('技术')?'技术':lower.includes('会议')?'会议':'通用';return {intent,entities,steps,confidence,sentiment,stance,scene}}
function composeReply(nlu,citations,userText){const citeText=citations.slice(0,2).map(c=>`《${c.title}》`).join('，');const entityText=nlu.entities.slice(0,3).map(e=>`${e.type}${e.value}`).join('，')||'无显著实体';const stepText=nlu.steps.slice(0,2).join('，');return `已解析你的请求：意图为「${nlu.intent}」，实体：${entityText}。参考资料：${citeText}。基于上述，建议：${stepText}。如果需要，我可以继续深入处理「${userText}」。`}
function handleApi(req,res,pathname){if(req.method==='OPTIONS'){return json(res,200,{ok:true})}if(pathname==='/api/citations'&&req.method==='POST'){readBody(req).then(b=>{const out=genCitations(b.query||'');json(res,200,{citations:out})});return}if(pathname==='/api/nlu'&&req.method==='POST'){readBody(req).then(b=>{const out=genNLU(b.text||'');json(res,200,{nlu:out})});return}if(pathname==='/api/chat'&&req.method==='POST'){readBody(req).then(b=>{const text=b.text||'';const cites=genCitations(text);const nlu=genNLU(text);const reply=composeReply(nlu,cites,text);json(res,200,{reply,citations:cites,nlu})});return}json(res,404,{error:'not_found'})}
const server=http.createServer((req,res)=>{const u=url.parse(req.url).pathname||'/';if(u.startsWith('/api/')){return handleApi(req,res,u)}let p=decodeURIComponent(u);if(p==='/'||p==='')p='/index.html';const fp=path.join(root,p.replace(/^[\\/]+/,''));serveFile(res,fp)})
server.on('error',err=>{if(err&&err.code==='EADDRINUSE'){server.listen(0)}else{process.exit(1)}})
server.on('listening',()=>{const addr=server.address().port;console.log(`Preview: http://localhost:${addr}/`)})
server.listen(port)
